# Generated by Django 5.2.6 on 2025-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
