# Generated by Django 5.2.6 on 2025-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
